language: python
os:
  - "linux"
  - "osx"
matrix:
  allow_failures:
    - os: osx
    - python: pypy
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"
  - "pypy"
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
#   - "pip install -r ./requirements.txt"
  - "pip install -r ./requirements/dev-locked.txt"

# command to run the dependencies
script:
  - "pytest tests/test_piper.py"
#   - "coverage run --source ./mrpiper tests/test_piper.py"
#   - "coveralls"

# command to run tests
# jobs:
#   include:
#     - stage: "General tests"
#       python: "3.6"
#       script: "pytest"
